### ISSUE TITLE
Refine and Document `ErgoGenerators.extensionKvGen()`

### ISSUE THREAD

**Issue by stenolog** [ergoplatform/ergo#2118]
- re https://github.com/ergoplatform/ergo/issues/2114

The sporadic failure of test `ErgoStateContextSpec` (issue #2114) uncovered problems with `ErgoGenerators.extensionKvGen()`

### Relevant Code

- see https://github.com/ergoplatform/ergo/pull/2116

### Tasks

- [ ] https://github.com/ergoplatform/ergo/issues/2117
- [ ] add in-code documentation to `ErgoGenerators.extensionKvGen()`
- [ ] revise code to handle the problems uncovered within #2114
  - Possibly introduce `extensionKvGenValidated()`

**Comment by kushti** [comment]
There is no problem with generator , for keyspace starting with 0 byte, length of values should be of 4 bytes, otherwise, tests with fail on extension section parsing due to 

```
def parseExtension(h: Height, extension: Extension): Try[Parameters] = Try {
    val paramsTable = extension.fields.flatMap { case (k, v) =>
      require(k.length == 2, s"Wrong key during parameters parsing in extension: $extension")
      if (k(0) == Extension.SystemParametersPrefix && k(1) != SoftForkDisablingRules) {
        require(v.length == 4, s"Wrong value during parameters parsing in extension: $extension")
```

and there's need to document (in EIP) key spaces and rules for them, not generator
