### ISSUE TITLE
Streamline Development Process

### ISSUE THREAD

**Issue by stenolog** [ergoplatform/ergo#2124]
(draft - issue is a work-document)

---
## Motivation

> Currently, development of core repositories is not transparent enough, and also not scalable. Maintenance of many
infrastructure related projects is done chaotically. 
https://www.ergoforum.org/t/ergodevs-r-d-dao-for-ergo-core/4663

## Goals

* Increase Transparency of Development
* Increase Development Speed
* Increase Overall Quality

## Tasks
- [ ] https://github.com/ergoplatform/ergo/pull/2126
- [ ] Provide Core Developer Documentation
  - [ ] Stabilize/Document Build-System
  - [ ] Stabilize/Document Test-System
  - [ ] Stabilize/Document CI-System
- [ ] Consider using github projects (e.g. a simple board to get an overview)
- [ ] Consider using "Discussions", Categories: General, Ideas (which can be voted on)
- ?

> [8:48 PM]kushti: I am for squashing the commits, composing policies for issues, code  styling, and then resolve releasing issue!
https://discord.com/channels/668903786361651200/669989266478202917/1209572336974565407

**Comment by stenolog** [comment]
Closing this, my understanding is that I've misinterpreted the statement re transparency/chaos on the forum.
